name: EmployeeFront DevSecOps Workflow

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Security Check
              run: npm audit


            - name: Running the app 
              run: npm run build --if-present

            

