name: EmployeeFront DevSecOps Workflow

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # - name: Package lock
            #   run: npm i --package-lock-only

            - name: Dependency install
              run: npm install

            - name: Running the app 
              run: npm run build 

            

