name: EmployeeFront DevSecOps Workflow

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    sonar_check:
        runs-on: ubuntu-latest
        steps:
            - name: Download files from the current repository
              uses: actions/checkout@v3.5.3

            - name: Use Node.js 18.x
              uses: actions/setup-node@v3.7.0
              with:
                node-version: '18'

            - name: Install Dependencies
              run: npm install

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                args: > 
                  -Dsonar.organization=imas0        
                  -Dsonar.projectKey=iMAS0_employeefrontend-fursan-track3          
                  -Dsonar.sources=            
                  -Dsonar.host.url=http://sonarcloud.io
    audit-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Download files from the current repository
              uses: actions/checkout@v3.5.3
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3.7.0
              with:
                node-version: '18'
                
            - uses: actions/checkout@v3
            - name: install dependencies
              run: npm install

            - name: npm audit
              run: npm audit --dry-run --json > audit.json

            - uses: actions/upload-artifact@v3
              with:
                name: audit
                path: audit.json
            
            

