name: EmployeeFront DevSecOps Workflow

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Download files from the current repository
              uses: actions/checkout@v3

            - name: Use Node.js 18.x
              uses: actions/setup-node@v3.7.0
              with:
                node-version: '18'

            - name: Dependency install
              run: npm install

            - name: CI
              run: npm ci --force

            - name: Running the app 
              run: npm run build

            

