name: EmployeeFront DevSecOps Workflow

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    sonar_check:
        runs-on: ubuntu-latest
        steps:
            - name: Download files from the current repository
              uses: actions/checkout@v3

            # - name: Use Node.js 18.x
            #   uses: actions/setup-node@v3.7.0
            #   with:
            #     node-version: '18'

            # - name: Install Dependencies
            #   run: npm install

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                args: > 
                  -Dsonar.organization=imas0        
                  -Dsonar.projectKey=iMAS0_employeefrontend-fursan-track3          
                  -Dsonar.sources=            
                  -Dsonar.host.url=http://sonarcloud.io
    scan:
        runs-on: ubuntu-latest
        steps:
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3.7.0
              with:
                node-version: '18'
                
            - uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci

            - name: npm audit
            - uses: oke-py/npm-audit-action@v2
              with:
                  json_flag: true
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            
            

